'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class WFSimulador02

    '''<summary>
    '''form1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''Label12 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label12 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LblNomeConveino control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LblNomeConveino As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ImgLogo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ImgLogo As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''LblEconomiaFinal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LblEconomiaFinal As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Label14 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label14 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LblFaturamentoMensalCartaoCredito01 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LblFaturamentoMensalCartaoCredito01 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''TxtTaxaAtualCartaoCredito control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtTaxaAtualCartaoCredito As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LblCustoAtualCartaoCredito control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LblCustoAtualCartaoCredito As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LblFaturamentoMensalCartaoDebito01 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LblFaturamentoMensalCartaoDebito01 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''TxtTaxaAtualCartaoDebito control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtTaxaAtualCartaoDebito As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LblCustoAtualCartaoDebito control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LblCustoAtualCartaoDebito As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LblFaturamentoTotalCartoes01 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LblFaturamentoTotalCartoes01 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LblCustoTotalSituacaoAtual control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LblCustoTotalSituacaoAtual As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LblFaturamentoMensalCartaoCredito02 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LblFaturamentoMensalCartaoCredito02 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LblTaxaCartaoCreditoConvenio control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LblTaxaCartaoCreditoConvenio As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LblCustoConvenioCartaoCredito control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LblCustoConvenioCartaoCredito As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LblValorEconomiaMensalConvenioCredito control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LblValorEconomiaMensalConvenioCredito As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LblValorEconomiaAnualConvenioCredito control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LblValorEconomiaAnualConvenioCredito As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LblFaturamentoMensalCartaoDebito02 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LblFaturamentoMensalCartaoDebito02 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LblTaxaCartaoDebitoConvenio control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LblTaxaCartaoDebitoConvenio As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LblCustoConvenioCartaoDebito control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LblCustoConvenioCartaoDebito As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LblValorEconomiaMensalConvenioDebito control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LblValorEconomiaMensalConvenioDebito As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LblValorEconomiaAnualConvenioDebito control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LblValorEconomiaAnualConvenioDebito As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LblFaturamentoTotalCartoes02 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LblFaturamentoTotalCartoes02 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LblCustoTotalParceriaConvenio control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LblCustoTotalParceriaConvenio As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LblValorEconomiaMensalConvenioFinal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LblValorEconomiaMensalConvenioFinal As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LblValorEconomiaAnualConvenioFinal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LblValorEconomiaAnualConvenioFinal As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LblMensagemConvenio control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LblMensagemConvenio As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ImageButton3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ImageButton3 As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''LblErro control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LblErro As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''TxtTaxaAdesaoMaquininhaAtual control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtTaxaAdesaoMaquininhaAtual As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LblValorDespesaAdesaoMaquininhaConvenio control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LblValorDespesaAdesaoMaquininhaConvenio As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LblValorEconomiaAnualAdesaoMaquininha control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LblValorEconomiaAnualAdesaoMaquininha As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''TxtValorAluguelMensalMaquininhaAtual control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtValorAluguelMensalMaquininhaAtual As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LblValorDespesaAluguelMensalMaquininhaConvenio control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LblValorDespesaAluguelMensalMaquininhaConvenio As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LblValorEconomiaMensalAluguelMaquininha control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LblValorEconomiaMensalAluguelMaquininha As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LblValorEconomiaAnualAluguelMaquininha control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LblValorEconomiaAnualAluguelMaquininha As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''TxtValorPacoteContaCorrenteAtual control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtValorPacoteContaCorrenteAtual As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LblValorDespesaPacoteContaCorrenteConvenio control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LblValorDespesaPacoteContaCorrenteConvenio As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LblValorEconomiaMensalPacoteContaCorrente control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LblValorEconomiaMensalPacoteContaCorrente As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LblValorEconomiaAnualPacoteContaCorrente control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LblValorEconomiaAnualPacoteContaCorrente As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''TxtValorLinhaDiscadaAtual control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtValorLinhaDiscadaAtual As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LblValorDespesaLinhaDiscadaConvenio control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LblValorDespesaLinhaDiscadaConvenio As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LblValorEconomiaMensalLinhaDiscada control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LblValorEconomiaMensalLinhaDiscada As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LblValorEconomiaAnualLinhaDiscada control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LblValorEconomiaAnualLinhaDiscada As Global.System.Web.UI.WebControls.Label
End Class
