'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class WFTEFSaibaMais

    '''<summary>
    '''Head1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Head1 As Global.System.Web.UI.HtmlControls.HtmlHead

    '''<summary>
    '''form1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''LblNomeConvenio2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LblNomeConvenio2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ImgLogoUnis control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ImgLogoUnis As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''ImgLogoStone control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ImgLogoStone As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''ImgLogoCappta control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ImgLogoCappta As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''LblNome control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LblNome As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LblNomeConvenio1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LblNomeConvenio1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LblNomeGrupo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LblNomeGrupo As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LblTaxaDebito control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LblTaxaDebito As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LblTaxaCreditoAVista control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LblTaxaCreditoAVista As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LblTaxaParcelado2a6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LblTaxaParcelado2a6 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LblTaxaParcelado7a12 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LblTaxaParcelado7a12 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LblAntAuto control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LblAntAuto As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LblTaxaAntecipacaoAutomatica control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LblTaxaAntecipacaoAutomatica As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LblAntPontual control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LblAntPontual As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LblTaxaAntecipacaoPontual control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LblTaxaAntecipacaoPontual As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LblBandeirasTaxa control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LblBandeirasTaxa As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''BtnSimulador control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnSimulador As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''LblMensalidadeEquipamento control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LblMensalidadeEquipamento As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''BtnAnexo3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnAnexo3 As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''BtnPortal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnPortal As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''LblNomeConvenio3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LblNomeConvenio3 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''BtnAderir control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnAderir As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''BtnAnexo1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnAnexo1 As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''BtnAnexo2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnAnexo2 As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''LblNomeConvenio4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LblNomeConvenio4 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''BtnAnexo4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnAnexo4 As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''LblRodapePagina control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LblRodapePagina As Global.System.Web.UI.WebControls.Label
End Class
